name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: |
          npm install -g node-gyp
          node-gyp install 14.15.4
          node install-node-deps.js
          
      - name: Install esy
        run: |
          npm install -g esy
          npm install -g windows-build-tools
          
      - name: Esy Install
        run: esy install
        
      - name: Esy Bootstrap
        run: esy bootstrap
      - name: Esy Build
        run: esy build
        
      - name: Windows Release
        shell: pwsh
        run: |
          ./scripts/windows/publish.ps1
      - name: Upload
        run: ls
