name: CI-windows

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: stable
          
      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake gcc-g++ libuv1
                              
      - name: Esy setup
        run: |
          npm install -g esy@latest
          npm install -g windows-build-tools@4.0.0
          npm install -g node-gyp
          node-gyp install 14.15.4
          node install-node-deps.js
          
      - name: Esy Install
        run: |
          esy install
          esy bootstrap
          esy build --verbosity=debug
      
      - name: Windows Publish
        run: |
          ./scripts/windows/publish.ps1
          tar -cvf AppDir.tar _publish
          
      - uses: actions/upload-artifact@v3
        with: 
          name: Oni2_win
          path: AppDir.tar
                   
