name: CI-windows

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: stable
          
              
      - name: Esy setup
        run: |
          npm install -g esy@latest
          npm install -g windows-build-tools@4.0.0
          npm install -g node-gyp
          node-gyp install 14.15.4
          node install-node-deps.js
          

          
      - name: Esy Install
        run: |
          esy install
          
      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: mingw64-x86_64-gcc-core mingw64-x86_64-gcc-g++ mingw64-x86_64-headers mingw64-x86_64-runtime mingw64-x86_64-winpthreads curl diff diffutils git m4 make patch unzip python bash cygwin-devel cmake gcc-g++ libuv1
          install-dir: "C:/npm/prefix/node_modules/esy/node_modules/esy-bash/.cygwin"
          
      - name: Esy Build
        run: |
          esy bootstrap
          esy build --verbosity=debug

      - uses: actions/upload-artifact@v3
        with: 
          name: Oni2_win_publish
          path: ./

      - name: Windows Publish
        run: |
          mkdir -p _release/win32
          powershell ./scripts/windows/publish.ps1
          tar -cvf AppDir.tar _publish

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
